"""Generated by `xime grpc client`. DO NOT EDIT."""
from __future__ import annotations

from collections.abc import AsyncIterator
from pathlib import Path

import grpc.aio

from xime.adapters.grpc.client import SdkRuntime
from ._models import FetchRequest, HashRequest, HashResponse, StoreRequest, StoreResponse

_runtime = SdkRuntime(Path(__file__).with_name("_descriptors.binpb"))


class VaultClient:
    """Generated client for gRPC service xime.default.VaultController."""

    def __init__(self, channel: grpc.aio.Channel) -> None:
        self._channel = channel

    def fetch(self, request: FetchRequest) -> AsyncIterator[bytes]:
        return _runtime.server_stream(
            self._channel,
            "/xime.default.VaultController/Fetch",
            request,
            "FetchRequest",
            "FetchChunk",
        )

    async def hash(self, request: HashRequest) -> HashResponse:
        return await _runtime.unary(
            self._channel,
            "/xime.default.VaultController/Hash",
            request,
            "HashRequest",
            HashResponse,
            "HashResponse",
        )

    async def store(
        self, request: StoreRequest, chunks: AsyncIterator[bytes]
    ) -> StoreResponse:
        return await _runtime.client_stream(
            self._channel,
            "/xime.default.VaultController/Store",
            request,
            "StoreChunk",
            StoreResponse,
            "StoreResponse",
            chunks,
        )
