"""Generated by `xime grpc client`. DO NOT EDIT."""
from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel


class FetchRequest(BaseModel):
    name: str
    parts: int


class HashRequest(BaseModel):
    text: str


class HashResponse(BaseModel):
    digest: str
    trace_id: UUID


class StoreRequest(BaseModel):
    name: str


class StoreResponse(BaseModel):
    name: str
    total_bytes: int


FetchRequest.model_rebuild()
HashRequest.model_rebuild()
HashResponse.model_rebuild()
StoreRequest.model_rebuild()
StoreResponse.model_rebuild()
